volumes:
  postgres-data:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_PASSWORD=password

  n8n:
    build:
      context: .
      dockerfile: n8n/.devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    ports:
      - 5678:5678
    command: npx n8n
    environment:
      DB_POSTGRESDB_HOST: postgres
      DB_TYPE: postgresdb
      DB_POSTGRESDB_PASSWORD: password

  mongodb:
    image: "mongo:latest"
    ports:
      - 27017:27017
      - 8085:8085
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  postgres-data:
