volumes:
  postgres-data:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"

  n8n:
    build:
      context: .
      dockerfile: n8n/.devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    ports:
      - 443:5678
    links:
      - mongodb
      - postgres
    command: npx n8n
    environment:
      DB_POSTGRESDB_HOST: "${DB_POSTGRESDB_HOST}"
      DB_TYPE: "${DB_TYPE}"
      DB_POSTGRESDB_PASSWORD: "${DB_POSTGRESDB_PASSWORD}"
      N8N_RUNNERS_ENABLED: 1
      N8N_SECURE_COOKIE: 0

  mongodb:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  postgres-data:
