volumes:
  postgres-data:

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - hayes-net
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"

  n8n:
    build:
      context: .
      dockerfile: n8n/.devcontainer/Dockerfile
    volumes:
      - ..:/workspaces:cached
    networks:
      - host
      - hayes-net
    ports:
      - 5678:5678
    command: npx n8n
    environment:
      DB_POSTGRESDB_HOST: "${DB_POSTGRESDB_HOST}"
      DB_TYPE: "${DB_TYPE}"
      DB_POSTGRESDB_PASSWORD: "${DB_POSTGRESDB_PASSWORD}"
      N8N_RUNNERS_ENABLED: 1
      N8N_SECURE_COOKIE: 0

  mongodb:
    image: "mongo:latest"
    networks:
      - hayes-net
    ports:
      - 27017:27017
      - 8085:8085
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  postgres-data:

networks:
  host:
    name: host
    external: true
  hayes-net:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "172.20.0.1"
    ipam:
      config:
        - subnet: "172.20.0.0/16"
